<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Compile Remove="Features\Admin\Factories\**" />
    <Compile Remove="Features\Admin\Services\**" />
    <Compile Remove="Features\Common\Dtos\**" />
    <Compile Remove="Features\Common\Queries\**" />
    <Compile Remove="Services\Implementations\**" />
    <EmbeddedResource Remove="Features\Admin\Factories\**" />
    <EmbeddedResource Remove="Features\Admin\Services\**" />
    <EmbeddedResource Remove="Features\Common\Dtos\**" />
    <EmbeddedResource Remove="Features\Common\Queries\**" />
    <EmbeddedResource Remove="Services\Implementations\**" />
    <None Remove="Features\Admin\Factories\**" />
    <None Remove="Features\Admin\Services\**" />
    <None Remove="Features\Common\Dtos\**" />
    <None Remove="Features\Common\Queries\**" />
    <None Remove="Services\Implementations\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HireFlow.Domain\HireFlow.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="MassTransit" Version="8.0.15" />
    <PackageReference Include="MediatR" Version="14.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.15" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="8.0.2" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
